### ISSUE TITLE
Jicofo config

### ISSUE THREAD

**Issue by timowevel1** [switnet-ltd/quick-jibri-installer#72] opened 2021-09-03 09:22 UTC
Hey,

I maybe found a little misconfiguration inside the jicofo.conf,

trusted-domains: recorder.domain 
doesnt work for me. Jibri wont catch and audio/video streams.
I changed it to:
trusted-domains: [recorder.domain]
and it works fine.

**Comment by timowevel1** [comment] 2021-09-03 13:59
Update, didnt fix it. Had the same issue on another installation. All ports are open, so there is no issue.

**Comment by Ark74** [comment] 2021-09-03 18:22
I found this recently,
https://community.jitsi.org/t/alert-beware-of-chrome-92/103444

Could this be the case?

I'm still not sure how to confirm or deny this, one instance I've found this issue, but my personal one jibri is working fine with chrome 92-93 so far.
I don't host huge meetings, mostly 1-1, or up to 5 people, so couldn't say, also my main browser is a firefox based version so no chrome on the equation.
One client is reporting issues when recording, while 2 have confirmed it works, weird case.

I need to dig deeper, if I confirm, maybe I will host a fixed version of chrome and mark it on hold for the installer.
Wanna help to figure this out?

**Comment by timowevel1** [comment] 2021-09-03 18:28
Hey, thanks for your answer.
I can confirm that for a few people/times I tried it it worked and a few times Jibri just didnt catch Audio/Video (you just see their avatars).
How can I help you?
________________________________

**Comment by Ark74** [comment] 2021-09-03 18:33
Well narrow it down will be a big help

- when does  it happen
- what users suffer this.
  - what were they using

> I can confirm that for a few people/times I tried it it worked and a few times Jibri just didnt catch Audio/Video (you just see their avatars).

Yeah that's the behavior I'm told, but we cant replicate it.
Not sure if is based on the OS, browser, connection xD

So far is a bit random.

**Comment by Ark74** [comment] 2021-09-03 18:34
Maybe is something introduced on the latest release.

**Comment by Ark74** [comment] 2021-09-06 10:03
From unstable, 

The format seems to be,

```
    trusted-domains: [ "recorder.domain.com" ]
```

This is an issue from upstream, will be fixed in coming updates.

**Closed as completed by Ark74** 2021-09-06 10:03 UTC
